#!/bin/sh

#------------------------------------------------------------------
# Author: nido
# More: < https://github.com/NIDObr >
# Version: 0.1.3-beta 12/07/2020
# Tested on:
#	GNU bash, versão 4.4.20(1)-release (x86_64-pc-linux-gnu)
# Info:
#	Defragments FAT systems.
#	POSIX compatible
# License: BSD-3-Clause License 
#------------------------------------------------------------------

#---------------------------------VARS-----------------------------

dir_mnt="/media/nido_defrage"
dir_tmp="/home/defrags2"

#---------------------------------HEADER---------------------------

[ "$USER" = 'root' ] || {	# ROOT?
	printf '%s\n' "Error run as ROOT!"
	exit 2
}
[ -z "$1" ] || {	#
	printf '%s\n' "Error especify device!"
}
[ -e "$1" ] || {
	printf '%s\n' "Specfied target \"""${1}""\", does not exit."
	exit 3
}
if [ ! -e "${dir_mnt}" ]&&[ ! -e "${dir_tmp}" ];then
	printf '%s\n' "Directories do not exist, creating..."
	mkdir "${dir_mnt}" "${dir_tmp}" && printf '%s\n' "Successfully created!"
fi
if grep -q "${1}" /proc/mounts;then
	dir_mnt=$(grep "${1}" /proc/mounts | awk -F " " '{print $2}')
else
	mount "${1}" "${dir_mnt}" || exit 4
fi
mv "${dir_mnt}"/* "${dir_tmp}" || exit 5
umount "${dir_mnt}" || exit 6
mkfs.vfat "${1}" || exit 7
mount "${1}" "${dir_mnt}" || exit 8
mv "${dir_tmp}"/* "${dir_mnt}/" || exit 9
umount "${dir_mnt}" || exit '10'
printf '%s\n' "Successfully defragmented!"
exit 0
